version: 2.1
jobs:
  say_hello:
    docker:
      - image: cimg/base:2022.05
        auth:
          username : ryoneme2
          password : $DOCKERHUB_PASSWORD
    steps:
      - run : echo "Say hello to YAML!"
  say_goodbye :
    docker:
      - image: cimg/base:2022.05 
        auth:
          username : ryoneme2
          password : $DOCKERHUB_PASSWORD
    steps:
      - run : echo "Say goodbye to YAML!"

workflows:
  hello and goodbye :
    jobs:
      - say_hello
      - say_goodbye