version: 2.1
orbs:
  node : circleci/node@5.0.3
  github-pages-orb: fernfernfern/github-pages-orb@0.0.10

jobs:
  install-n-test:
    executor : 
      name : node/default
      tag : '16.17'
    steps:
      - checkout
      - node/install-packages
      - run : 'npm run test'
workflows:
  test-my-app:
    jobs:
      - install-n-test
      - github-pages-orb