version: 2.1
orbs:
  nodes : circleci/node@5.0.3

jobs:
  install-and-test:
    executor : 
      name : node/default
      tag : '16.17'
    steps:
      - checkout
      - node/install-packages:
          pkg-manager : yarn
      - run : 'yarn test'

workflows:
  test-my-app:
    jobs:
      - install-and-test