version: 2.1
orbs:
  node : circleci/node@5.0.3
  gh-pages: sugarshin/gh-pages@1.0.1

jobs:
  install-n-test:
    executor : 
      name : node/default
      tag : '16.17'
    steps:
      - checkout
      - node/install-packages :
          pkg-manager : yarn
      - run : 'yarn test'
  gh-page : 
    build_deploy:
    executor: gh-pages/default
    steps:
      - checkout
      - run : pwd && ls -l
      - run : sudo ./build.sh
      - gh-pages/deploy:
          setup-git: true
          ssh-fingerprints: ${MY_FINGER_PRINT}

workflows:
  test-my-app:
    jobs:
      - install-n-test
      - gh-page :
          context: Credential
