version: 2.1
orbs:
  node : circleci/node@5.0.3

jobs:
  install-and-test:
    executor : 
      name : node/default
      tag : '16.17'
    steps:
      - checkout
      - node/install-packages
      - run : 'npm run test'

workflows:
  test-my-app:
    jobs:
      - install-and-test