version: 2.1
orbs:
  node : circleci/node@5.0.3
  gh-pages: sugarshin/gh-pages@1.0.1

jobs:
  install-n-test:
    executor : 
      name : node/default
      tag : '16.17'
    steps:
      - checkout
      - node/install-packages :
          pkg-manager : yarn
      - run :
          name : Testing
          command: yarn test
      - run :
          name : Build
          command: PUBLIC_URL=/cicd-circleCI yarn build

workflows:
  test-my-app:
    jobs:
      - install-n-test
      - gh-pages/deploy:
          context: Credential
          requires:
            - install-n-test
          ssh-fingerprints: ${MY_FINGER_PRINT}
          
