version: 2.1
orbs:
  node : circleci/node@5.0.3
  github-pages-orb: fernfernfern/github-pages-orb@0.0.10

jobs:
  install-n-test:
    executor : 
      name : node/default
      tag : '16.17'
    steps:
      - checkout
      - node/install-packages :
          pkg-manager : pnpm
          with-cache : true
      - run : 'npm run test'
  gh-page : 
    build_deploy:
    docker:
      - image: cimg/node:16.17.1
        auth:
          username: Ryoneme2
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - node/install-packages # Utilize commands in steps
      - run : npm run build

workflows:
  test-my-app:
    jobs:
      - install-n-test
      - gh-page 
