version: 2.1
orbs:
  node : circleci/node@5.0.3
  gh-pages: sugarshin/gh-pages@1.0.1

jobs:
  install-n-test:
    executor : 
      name : node/default
      tag : '16.17'
    steps:
      - checkout
      - node/install-packages :
          pkg-manager : yarn
      - run :
          name : Testing
          command: yarn test
      - run :
          name : Build
          command: PUBLIC_URL=/cicd-circleCI yarn build
  deploy : 
    executor : 
      name : node/default
      tag : '16.17'
    steps:
      - checkout
      - node/install-packages :
          pkg-manager : yarn
      - run : PUBLIC_URL=/cicd-circleCI yarn build
      - add_ssh_keys:
          fingerprints:
            - "f6:69:5c:ab:8f:ca:0d:e3:f5:db:f5:da:01:89:fd:bd"
      - run : |
          cd ./build
          git init -b gh-pages
          git remote add -t gh-pages origin https://git:@github.com/Ryoneme2/cicd-circleCI.git
          git fetch -u origin gh-pages:gh-pages
          git add .
          git commit -m "circle bot deploy" || echo "nothing change on commit && exit 0"
          git push origin gh-pages -f
          cd .. 

workflows:
  test-my-app:
    jobs:
      - install-n-test
      - deploy
          
          
          
